version: '3.8'

services:
  app:
    image: golang:1.23.1
    container_name: go_app
    environment:
      JWT_KEY: "secret"
    working_dir: /app
    volumes:
      - .:/app
    command: go run main.go
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: canoe_reddit_integration
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/repository/postgres/migration:/docker-entrypoint-initdb.d

volumes:
  postgres_data: